<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Cek_faktur extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
		$this->load->library('DX_Auth');
		$this->load->helper('form');
		$this->load->helper('url');
		
		$this->load->model('umum');
        $this->load->model('Tag_usaha_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
		$this->session->set_flashdata('message', 'GAGAL membuat QR code');
        redirect(site_url('tag_pelanggan'));
    }
	
	public function valid()
    {
        $data['qrcode'] = $this->uri->segment(3);
        $this->load->view('global/cek_faktur', $data);
    }
	

}

/* End of file Tag_usaha.php */
/* Location: ./application/controllers/Tag_usaha.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-12-14 05:29:00 */
/* http://harviacode.com */